#!/usr/bin/env python3
# Embeds the constructor half of ci/api.tl (Telegram's TL schema, from tdesktop's
# Telegram/SourceFiles/mtproto/scheme/api.tl, layer 229 — the layer Telegram iOS 12.9.4 speaks)
# into the dylib for AYTLWalker. Output is committed; CI re-runs this and fails if it's stale.
import os, re, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, 'ci/api.tl')
out = os.path.join(root, 'Sources/tgapi/TLSchemaData.swift')

text = open(src, encoding='utf-8').read()
layer = re.search(r'//\s*LAYER\s+(\d+)', text).group(1)
constructors = text.split('---functions---')[0]
lines = []
for raw in constructors.splitlines():
    line = raw.split('//')[0].strip()
    # Only concrete constructors; skips builtins ("int ? = Int;") and the generic vector.
    if re.match(r'^[a-zA-Z0-9_.]+#[0-9a-f]+\b', line) and '{' not in line:
        line = line.rstrip(';').strip()
        assert '"' not in line and '\\' not in line, line
        lines.append(line)

body = '\n'.join(lines)
code = ('// Generated by ci/gen_tl.py from ci/api.tl — do not edit.\n'
        '// TL constructors of layer %s, one per line: name#id field:type ... = Type\n\n'
        'let AYTLSchemaLayer = %s\n\n'
        'let AYTLSchemaText = """\n%s\n"""\n') % (layer, layer, body)

if '--check' in sys.argv:
    if not os.path.exists(out) or open(out, encoding='utf-8').read() != code:
        sys.exit('TLSchemaData.swift is stale: run ci/gen_tl.py')
else:
    open(out, 'w', encoding='utf-8').write(code)
    print('%d constructors, layer %s' % (len(lines), layer))
