#!/usr/bin/env python3
# Embeds ayTELE.bundle's strings and language list into the dylib, so swapping only
# the dylib (sideload) still brings its own translations. Output is committed;
# CI re-runs this and fails if the committed file is stale.
import json, os, re, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
bundle = os.path.join(root, 'ayTELE.bundle')
out = os.path.join(root, 'Sources/tgapi/UI/EmbeddedStrings.m')
pair = re.compile(r'^\s*"((?:\\.|[^"\\])*)"\s*=\s*"((?:\\.|[^"\\])*)"\s*;\s*$')

def lit(s):
    return '@"' + s + '"'  # already C-escaped in the .strings source

langs = json.load(open(os.path.join(bundle, 'langs.json'), encoding='utf-8'))
lines = ['// Generated by ci/gen_strings.py from ayTELE.bundle — do not edit.',
         '#import "Headers.h"', '',
         'NSArray<NSDictionary *> *AYEmbeddedLanguages(void) {', '\treturn @[']
for l in langs:
    lines.append('\t\t@{@"name": %s, @"code": %s, @"flag": %s},' % (lit(l['name']), lit(l['code']), lit(l['flag'])))
lines += ['\t];', '}', '',
          'NSDictionary<NSString *, NSString *> *AYEmbeddedStrings(NSString *code) {']
for l in langs:
    code = l['code']
    path = os.path.join(bundle, code + '.lproj', 'Localizable.strings')
    if not os.path.exists(path):
        continue
    lines.append('\tif ([code isEqualToString:%s]) return @{' % lit(code))
    for raw in open(path, encoding='utf-8'):
        m = pair.match(raw.rstrip('\n'))
        if m:
            lines.append('\t\t%s: %s,' % (lit(m.group(1)), lit(m.group(2))))
    lines.append('\t};')
lines += ['\treturn nil;', '}', '']
text = '\n'.join(lines)

if '--check' in sys.argv:
    if not os.path.exists(out) or open(out, encoding='utf-8').read() != text:
        sys.exit('EmbeddedStrings.m is stale: run ci/gen_strings.py')
else:
    open(out, 'w', encoding='utf-8').write(text)
