name: CI test
on:
  push:
    branches: [ci-test]
jobs:
  filter-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Run filter tests
        run: |
          swiftc -O -o filtertest Sources/tgapi/api_sources/*.swift Sources/tgapi/DeletedMessages.swift Sources/tgapi/EditHistory.swift Sources/tgapi/MessageDetails.swift Sources/tgapi/Notes.swift ci/main.swift
          ./filtertest
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Theos
        uses: waruhachi/theos-action@v2.4.6
        with:
          theos-src: 'waruhachi/theos'
          theos-branch: 'main'
          sdks-src: 'waruhachi/sdks'
          sdks-branch: 'main'
      - name: Build Package
        run: |
          make clean package FINALPACKAGE=1 STRIP=0 THEOS_PACKAGE_SCHEME=rootless
          make clean package FINALPACKAGE=1 STRIP=0
      - uses: actions/upload-artifact@v4
        with:
          name: debs
          path: |
            packages/*.deb
            .theos/obj/**/*.dylib
